export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SUCCESS_USER_DETAIL = "SUCCESS_USER_DETAIL";
export const REQUEST_USER_DETAIL = "REQUEST_USER_DETAIL";
export const FAIL_USER_DETAIL = "FAIL_USER_DETAIL";
export const LOGIN_ERROR_CLEAR = "LOGIN_ERROR_CLEAR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
